"use server";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireServerUser } from "@/lib/auth/server-guard";
import { createClient } from "@/lib/supabase/server";

const schema=z.object({agencyName:z.string().trim().min(2).max(120),website:z.string().trim().max(240).refine(v=>!v||/^https?:\/\//i.test(v),"Use a complete http(s) website URL."),market:z.string().trim().min(2).max(120),currency:z.string().trim().regex(/^[A-Z]{3}$/),packagePrice:z.string().trim().min(1).max(40),tone:z.enum(["Friendly","Direct","Premium","Soft sell","Confident","Local business friendly"]),goal:z.string().trim().min(2).max(240)});

export type OnboardingState={error?:string};
export async function completeOnboarding(_state:OnboardingState,formData:FormData):Promise<OnboardingState>{const parsed=schema.safeParse({agencyName:formData.get("agencyName"),website:formData.get("website"),market:formData.get("market"),currency:formData.get("currency"),packagePrice:formData.get("packagePrice"),tone:formData.get("tone"),goal:formData.get("goal")});if(!parsed.success)return{error:parsed.error.issues[0]?.message||"Review the onboarding fields."};const user=await requireServerUser();const supabase=await createClient();if(!supabase||user.mode!=="remote")redirect("/dashboard");const profile=await supabase.from("user_profiles").upsert({user_id:user.userId,agency_name:parsed.data.agencyName,main_website:parsed.data.website,primary_market:parsed.data.market,primary_goal:parsed.data.goal},{onConflict:"user_id"});if(profile.error)return{error:"Your profile could not be saved. Confirm that the public-beta migration has been applied."};const settings=await supabase.from("app_settings").upsert({user_id:user.userId,company_name:parsed.data.agencyName,website:parsed.data.website,default_currency:parsed.data.currency,default_package_price:parsed.data.packagePrice,default_message_tone:parsed.data.tone},{onConflict:"user_id"});if(settings.error)return{error:"Your workspace defaults could not be saved."};const progress=await supabase.from("onboarding_progress").upsert({user_id:user.userId,profile_completed:true},{onConflict:"user_id"});if(progress.error)return{error:"Onboarding progress could not be saved."};redirect("/create?firstProject=1")}

const progressStepSchema=z.enum(["lead_added","facts_verified","first_demo_generated","first_demo_reviewed","first_outreach_prepared"]);
export async function markOnboardingProgress(step:z.infer<typeof progressStepSchema>){const safeStep=progressStepSchema.parse(step);const user=await requireServerUser();const supabase=await createClient();if(!supabase||user.mode!=="remote")return{configured:false};const{error}=await supabase.from("onboarding_progress").upsert({user_id:user.userId,[safeStep]:true},{onConflict:"user_id"});if(error)throw new Error("Onboarding progress could not be saved.");return{configured:true}}
