import { describe, expect, it } from "vitest";
import { GenerationBudget, GenerationBudgetExceededError } from "@/lib/generation/pipeline/generation-budget";
import { completePagePrompt, extractHtml } from "@/lib/generation/pipeline/generate-complete-page";
import { unifiedSiteBriefSchema } from "@/lib/generation/pipeline/types";
import { buildBusinessContext, fallbackUnifiedBrief } from "@/lib/generation/pipeline/unified-brief";
import { validateGeneratedHtml } from "@/lib/generation/pipeline/validate-output";
import { isEventForGeneration, isValidEventOrder, usageStatusForPipelineOutcome } from "@/lib/generation/pipeline/events";
import { getRoutesForStage } from "@/lib/ai/modelRouter";
import { generationFixtures } from "./fixtures/generation-businesses";

const brief = unifiedSiteBriefSchema.parse({ businessSummary: "A locally focused restaurant.", verifiedFacts: ["Name: Harbor Table"], missingOrUncertainFacts: ["Hours are not verified."], targetAudience: "Local diners", primaryConversionAction: "Call Harbor Table", visualThesis: "Warm editorial dining room", brandPersonality: "Welcoming and refined", colorAndTypographyDirection: "Terracotta with warm serif headlines", imageAssetStrategy: "Use supplied photography only; otherwise restrained CSS composition.", pageNarrative: "Arrival, offering, visit, contact.", sectionOutline: [{ name: "Welcome", purpose: "Introduce the restaurant" }, { name: "Offering", purpose: "Describe verified offerings" }, { name: "Visit", purpose: "Present contact details" }, { name: "Contact", purpose: "Prompt a call" }], copyDirection: "Specific and sensory without unverified claims.", seoRequirements: ["Title", "Description"], accessibilityRequirements: ["Semantic landmarks", "Focus states", "Alt text"], factualRestrictions: ["No reviews", "No prices", "No awards"], responsiveBehavior: ["Single-column mobile", "No fixed overflow", "Touch-friendly CTA"] });

function inputFor(fixture: typeof generationFixtures[keyof typeof generationFixtures]) {
  return { generationId: "test-generation", generationDepth: "fast-draft" as const, generationMode: "standard", business: { name: fixture.name, description: `${fixture.category} in ${fixture.location}`, targetAudience: "Local customers", differentiators: fixture.services.split(", "), brandPersonality: "Warm" }, info: { rawInfo: "", businessName: fixture.name, category: fixture.category, location: fixture.location, phone: "555-0100", email: "hello@example.test", websiteUrl: "", socialUrl: "", services: fixture.services, brandColors: "#9B3D2E, #E5A33A", notes: "" }, sourceImageDataUrl: "" };
}

describe("unified complete-page pipeline", () => {
  it("validates the strict unified brief contract", () => { expect(unifiedSiteBriefSchema.safeParse(brief).success).toBe(true); expect(unifiedSiteBriefSchema.safeParse({ businessSummary: "x" }).success).toBe(false); });
  it("enforces Fast and Premium call budgets while retaining failure capacity", () => { const fast = new GenerationBudget("fast-draft"); fast.consumeCall("brief"); fast.consumeCall("page"); expect(fast.snapshot().aiCalls).toBe(2); const premium = new GenerationBudget("premium-final"); for (let i = 0; i < 6; i += 1) premium.consumeCall("stage"); expect(() => premium.consumeCall("overflow")).toThrow(GenerationBudgetExceededError); });
  it("enforces one repair and one retry maximum", () => { const budget = new GenerationBudget("premium-final"); budget.consumeCall("repair", true); expect(() => budget.consumeCall("repair", true)).toThrow(GenerationBudgetExceededError); budget.consumeRetry("page"); expect(() => budget.consumeRetry("page")).toThrow(GenerationBudgetExceededError); });
  it("uses one primary and at most one fallback model route", () => { const routes = getRoutesForStage("complete-page"); expect(routes.length).toBeLessThanOrEqual(2); expect(routes.filter((route) => route.fallback)).toHaveLength(Math.min(1, Math.max(0, routes.length - 1))); });
  it("keeps public stream stages ordered and rejects stale generation events", () => { const events = ["understanding-business", "planning-site", "generating-website", "checking-output", "complete"].map((type) => ({ type })) as never; expect(isValidEventOrder(events)).toBe(true); expect(isValidEventOrder([{ type: "generating-website" }, { type: "planning-site" }] as never)).toBe(false); expect(isEventForGeneration("active", { generationId: "active" })).toBe(true); expect(isEventForGeneration("active", { generationId: "stale" })).toBe(false); });
  it("completes usage only for completed pages and refunds failed reservations", () => { expect(usageStatusForPipelineOutcome(true)).toBe("succeeded"); expect(usageStatusForPipelineOutcome(false)).toBe("refunded"); });
  it("builds complete-page instructions instead of section prompts", () => { const context = buildBusinessContext(inputFor(generationFixtures.restaurant)); const prompt = completePagePrompt(context, brief); expect(prompt).toMatch(/COMPLETE standalone index\.html/i); expect(prompt).not.toMatch(/generate the next section/i); expect(extractHtml("```html\n<!doctype html><html></html>\n```")).toMatch(/^<!doctype/i); });
  it("falls back to a valid deterministic brief when a planner response is malformed", () => { const context = buildBusinessContext(inputFor(generationFixtures.restaurant)); const fallback = fallbackUnifiedBrief(context); expect(unifiedSiteBriefSchema.safeParse(fallback).success).toBe(true); expect(fallback.verifiedFacts).toContain(context.name); });
  it("repairs only fatal deterministic defects and leaves valid output alone", () => { const context = buildBusinessContext(inputFor(generationFixtures.autoService)); const valid = `<!doctype html><html><head><title>${context.name}</title><meta name="description" content="Auto care"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex, nofollow"><meta property="og:title" content="${context.name}"><style>body{margin:0}a:focus{outline:2px solid}</style></head><body><main><h1>${context.name}</h1><p>Vehicle maintenance and diagnostics.</p><a href="tel:555-0100">Call us</a></main></body></html>`; expect(validateGeneratedHtml(valid, context).fatal).toBe(false); const broken = validateGeneratedHtml(`<html><body><h1>${context.name}</h1><img src="x"></body></html>`, context); expect(broken.fatal).toBe(true); expect(broken.findings.some((item) => item.code === "MISSING_ALT")).toBe(true); });
  it("preserves verified facts and rejects fabricated claims for each representative industry", () => { for (const fixture of Object.values(generationFixtures)) { const context = buildBusinessContext(inputFor(fixture)); const html = `<!doctype html><html><head><title>${context.name}</title><meta name="description" content="${fixture.category}"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex, nofollow"><style>body{overflow-x:hidden}a:focus{outline:2px solid}</style></head><body><main><h1>${context.name}</h1><p>${fixture.services}</p></main></body></html>`; expect(validateGeneratedHtml(html, context).fatal).toBe(false); expect(validateGeneratedHtml(html.replace(fixture.services, "Award-winning five-star service"), context).findings.some((item) => item.code === "FABRICATED_CLAIM")).toBe(true); } });
});
