"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { AuthFrame } from "@/components/auth-frame";
import { Button } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
export function ForgotPasswordForm(){const[email,setEmail]=useState("");const[loading,setLoading]=useState(false);const[sent,setSent]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();const s=createClient();if(!s){toast.error("Password recovery is unavailable until Supabase is configured.");return}setLoading(true);const{error}=await s.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});setLoading(false);if(error){toast.error("Password recovery could not be started.");return}setSent(true)};return <AuthFrame title="Reset your password" description="Enter your account email. If it exists, Supabase will send a secure recovery link.">{sent?<div className="mt-8 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-900">Check your inbox for a recovery link.</div>:<form className="mt-8" onSubmit={submit}><label><span className="field-label">Email address</span><input className="field-input" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><Button className="mt-5 w-full" type="submit" loading={loading}>Send recovery link</Button></form>}<p className="mt-5 text-center text-xs"><Link href="/login" className="font-bold text-brand-700">Back to sign in</Link></p></AuthFrame>}
export function ResetPasswordForm(){const[password,setPassword]=useState("");const[loading,setLoading]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();const s=createClient();if(!s)return;setLoading(true);const{error}=await s.auth.updateUser({password});setLoading(false);if(error){toast.error("Your password could not be updated. Request a new recovery link.");return}toast.success("Password updated.");window.location.href="/dashboard"};return <AuthFrame title="Choose a new password" description="Your recovery link must still be active. Use a unique password with at least 10 characters."><form className="mt-8" onSubmit={submit}><label><span className="field-label">New password</span><input className="field-input" type="password" autoComplete="new-password" minLength={10} required value={password} onChange={e=>setPassword(e.target.value)}/></label><Button className="mt-5 w-full" type="submit" loading={loading}>Update password</Button></form></AuthFrame>}
