"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { AuthFrame } from "@/components/auth-frame";
import { Button } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import { friendlyAuthError } from "@/lib/auth/errors";

export function SignupForm(){const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [loading,setLoading]=useState(false);const [sent,setSent]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();const supabase=createClient();if(!supabase){toast.error("Account creation is unavailable until Supabase is configured.");return}setLoading(true);const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/auth/callback?next=/onboarding`}});setLoading(false);if(error){toast.error(friendlyAuthError(error.message));return}if(data.session){window.location.href="/onboarding";return}setSent(true)};return <AuthFrame title="Create your account" description="Start with public-beta access. You will verify your email, then complete a short workspace setup.">{sent?<div className="mt-8 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm leading-6 text-emerald-900"><strong>Check your email.</strong><p className="mt-1">Use the verification link to activate your account and continue onboarding.</p></div>:<form onSubmit={submit} className="mt-8 space-y-4"><label><span className="field-label">Email address</span><input className="field-input" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label><span className="field-label">Password</span><input className="field-input" type="password" autoComplete="new-password" minLength={10} required value={password} onChange={e=>setPassword(e.target.value)}/><span className="mt-1 block text-xs text-[#858b9d]">Use at least 10 characters.</span></label><Button className="w-full min-h-11" type="submit" loading={loading}>Create account</Button><p className="text-center text-xs leading-5 text-[#747b8f]">By continuing, you agree to the <Link href="/terms" className="font-bold text-brand-700">Terms</Link> and <Link href="/acceptable-use" className="font-bold text-brand-700">Acceptable Use Policy</Link>.</p></form>}<p className="mt-5 text-center text-xs">Already have an account? <Link href="/login" className="font-bold text-brand-700">Sign in</Link></p></AuthFrame>}
