import type { ActivityItem, AppSettings, Prospect } from "@/lib/types";

export const DEFAULT_SETTINGS: AppSettings = {
  companyName: "Niche Technologies",
  senderName: "Chad",
  senderEmail: "",
  whatsappNumber: "",
  website: "",
  defaultPackagePrice: "$1,000",
  defaultCurrency: "USD",
  defaultTone: "Friendly",
  defaultWebsiteStyle: "Editorial premium",
  mailingAddress: "",
};

export const MOCK_PROSPECTS: Prospect[] = [
  {
    id: "prospect-1",
    business_name: "Kingston Bloom Studio",
    category: "Florist",
    location: "Kingston",
    phone: "+1 876 555 0184",
    email: "hello@kingstonbloom.example",
    website_url: "",
    social_url: "https://instagram.com/kingstonbloom",
    pasted_raw_info: "Kingston Bloom Studio. Custom bouquets and event florals in Kingston.",
    extracted_summary: "A Kingston florist focused on custom bouquets and event florals.",
    package_price: "$1,000",
    generated_website_html: "",
    demo_url: "https://kingston-bloom-demo.vercel.app",
    whatsapp_message: "Hi Kingston Bloom Studio, I prepared a custom website concept for your business.",
    email_subject: "Website concept for Kingston Bloom Studio",
    email_message: "I prepared a custom website concept to show how your services could be presented online.",
    dm_message: "Hi, I put together a website concept for Kingston Bloom Studio.",
    outreach_status: "replied",
    notes: "Interested in seeing a mobile-first version.",
    created_at: "2026-06-10T14:20:00.000Z",
    updated_at: "2026-06-13T10:00:00.000Z",
    last_contacted_at: "2026-06-12T15:30:00.000Z",
    next_follow_up_at: "2026-06-16T14:00:00.000Z",
  },
  {
    id: "prospect-2",
    business_name: "North Coast Auto Care",
    category: "Auto repair",
    location: "St. Ann",
    phone: "+1 876 555 0112",
    email: "",
    website_url: "",
    social_url: "https://facebook.com/northcoastautocare",
    pasted_raw_info: "North Coast Auto Care - diagnostics, servicing, brakes, AC repair.",
    extracted_summary: "An auto repair business in St. Ann offering diagnostics and general servicing.",
    package_price: "$1,250",
    generated_website_html: "",
    demo_url: "",
    whatsapp_message: "",
    email_subject: "",
    email_message: "",
    dm_message: "",
    outreach_status: "not_sent",
    notes: "",
    created_at: "2026-06-12T09:15:00.000Z",
    updated_at: "2026-06-12T09:15:00.000Z",
    last_contacted_at: null,
    next_follow_up_at: null,
  },
  {
    id: "prospect-3",
    business_name: "Harbour View Dental",
    category: "Dental clinic",
    location: "Kingston",
    phone: "+1 876 555 0198",
    email: "care@harbourviewdental.example",
    website_url: "https://harbourviewdental.example",
    social_url: "",
    pasted_raw_info: "Harbour View Dental. General and family dentistry.",
    extracted_summary: "A Kingston dental clinic offering general and family dentistry.",
    package_price: "$1,500",
    generated_website_html: "<!doctype html><html><body>Demo generated</body></html>",
    demo_url: "https://harbour-view-dental-demo.vercel.app",
    whatsapp_message: "Hi Harbour View Dental, I prepared a private website concept for your clinic.",
    email_subject: "Private website concept for Harbour View Dental",
    email_message: "I prepared a private concept showing a clearer mobile experience for prospective patients.",
    dm_message: "Hi, I prepared a private website concept for Harbour View Dental.",
    outreach_status: "sent",
    notes: "Follow up by email.",
    created_at: "2026-06-08T11:00:00.000Z",
    updated_at: "2026-06-11T16:30:00.000Z",
    last_contacted_at: "2026-06-11T16:30:00.000Z",
    next_follow_up_at: "2026-06-15T15:00:00.000Z",
  },
  {
    id: "prospect-4",
    business_name: "Studio Nine Interiors",
    category: "Interior design",
    location: "Montego Bay",
    phone: "",
    email: "studio@studionine.example",
    website_url: "https://studionine.example",
    social_url: "https://instagram.com/studionine",
    pasted_raw_info: "Studio Nine Interiors, Montego Bay. Residential interiors.",
    extracted_summary: "A Montego Bay studio focused on residential interior design.",
    package_price: "$1,800",
    generated_website_html: "<!doctype html><html><body>Demo generated</body></html>",
    demo_url: "https://studio-nine-concept.vercel.app",
    whatsapp_message: "",
    email_subject: "A website concept for Studio Nine Interiors",
    email_message: "",
    dm_message: "",
    outreach_status: "won",
    notes: "Approved starter package.",
    created_at: "2026-05-29T13:00:00.000Z",
    updated_at: "2026-06-09T18:00:00.000Z",
    last_contacted_at: "2026-06-09T18:00:00.000Z",
    next_follow_up_at: null,
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: "activity-1",
    prospectId: "prospect-1",
    prospectName: "Kingston Bloom Studio",
    action: "Reply received",
    detail: "Prospect asked to see the mobile version.",
    createdAt: "2026-06-13T10:00:00.000Z",
  },
  {
    id: "activity-2",
    prospectId: "prospect-3",
    prospectName: "Harbour View Dental",
    action: "Message sent",
    detail: "Email draft opened and marked as sent.",
    createdAt: "2026-06-11T16:30:00.000Z",
  },
  {
    id: "activity-3",
    prospectId: "prospect-4",
    prospectName: "Studio Nine Interiors",
    action: "Marked won",
    detail: "Starter website package approved.",
    createdAt: "2026-06-09T18:00:00.000Z",
  },
  {
    id: "activity-4",
    prospectId: "prospect-2",
    prospectName: "North Coast Auto Care",
    action: "Prospect created",
    detail: "Business information parsed and saved.",
    createdAt: "2026-06-12T09:15:00.000Z",
  },
];
