import { ApiError } from "@/lib/security/api-error";
import { createClient } from "@/lib/supabase/server";
import type { ServerUserAccess } from "@/lib/auth/server-guard";
import { createAdminClient } from "@/lib/supabase/admin";
import { serverLog } from "@/lib/observability/logger";

export const usageOperations=["screenshot_extraction","lead_search","fast_generation","premium_generation","regeneration","outreach_generation","deployment"] as const;
export type UsageOperation=(typeof usageOperations)[number];
export type UsageReservation={eventId:string|null;userId:string;operation:UsageOperation;used:number;limit:number;replay:boolean};
const defaultCostEstimates:Record<UsageOperation,number>={screenshot_extraction:0.01,lead_search:0.02,fast_generation:0.12,premium_generation:0.45,regeneration:0.05,outreach_generation:0.01,deployment:0.001};
export function estimatedOperationCost(operation:UsageOperation){const key=`COST_ESTIMATE_${operation.toUpperCase()}_USD`;const configured=Number(process.env[key]);return Number.isFinite(configured)&&configured>=0?configured:defaultCostEstimates[operation]}

export async function reserveUsage(user:ServerUserAccess,operation:UsageOperation,key:string,requestId:string):Promise<UsageReservation>{if(user.mode==="local-demo")return{eventId:null,userId:user.userId,operation,used:0,limit:100000,replay:false};const admin=createAdminClient();if(!admin)throw new ApiError("ENTITLEMENTS_UNAVAILABLE","Usage enforcement is not fully configured. No provider request was started.",503);const supabase=user.mode==="worker"?admin:await createClient();if(!supabase)throw new ApiError("ENTITLEMENTS_UNAVAILABLE","Usage enforcement is unavailable.",503);const rpc=user.mode==="worker"?"consume_usage_for_user":"consume_usage";const params=user.mode==="worker"?{p_user_id:user.userId,p_operation:operation,p_idempotency_key:key,p_request_id:requestId}:{p_operation:operation,p_idempotency_key:key,p_request_id:requestId};const{data,error}=await supabase.rpc(rpc,params);if(error)throw new ApiError("ENTITLEMENTS_UNAVAILABLE","Usage could not be verified. No provider request was started.",503);const row=Array.isArray(data)?data[0]:data;if(!row?.allowed)throw new ApiError(row?.reason==="quota_exceeded"?"QUOTA_EXCEEDED":"NOT_ENTITLED",row?.reason==="quota_exceeded"?`Your ${operation.replaceAll("_"," ")} allowance is used for this period.`:"This operation is not included in the current plan.",402);if(row.reason==="idempotent_replay")throw new ApiError("DUPLICATE_REQUEST","This operation is already running or completed. Refresh the project before trying again.",409);return{eventId:row.event_id||null,userId:user.userId,operation,used:Number(row.used||0),limit:Number(row.limit_value||0),replay:false}}
export async function completeUsage(reservation:UsageReservation,status:"succeeded"|"failed"|"refunded",metadata:{estimatedCostUsd?:number;provider?:string;model?:string;errorCode?:string}={}){if(!reservation.eventId)return;const admin=createAdminClient();if(!admin)return;const cost=metadata.estimatedCostUsd??(status==="succeeded"?estimatedOperationCost(reservation.operation):0);const{error}=await admin.from("usage_events").update({status,estimated_cost_usd:Math.max(cost,0),provider:(metadata.provider||"").slice(0,80),model:(metadata.model||"").slice(0,120),error_code:(metadata.errorCode||"").slice(0,80),completed_at:new Date().toISOString()}).eq("id",reservation.eventId).eq("user_id",reservation.userId).eq("status","reserved");if(error)serverLog("error","usage.completion_failed",{operation:reservation.operation,status})}

export function operationForGeneration(depth:"fast-draft"|"premium-final"):UsageOperation{return depth==="premium-final"?"premium_generation":"fast_generation"}
